package compilador;

public enum Tokens{
    LONG, DOUBLE, NUMERO_LONG, NUMERO_DOUBLE, MAS, MENOS, POR, DIVISION, IGUAL,
    DISTINTO, MAYOR, MENOR, MENORIGUAL, MAYORIGUAL, ASIGNADOR, MASUNO, MENOSUNO,
    MASNUMERO, MENOSNUMERO, PARIZQ, PARDER, COMA, PYCOMA, WRITE, READ, WHILE, LLAVEIZQ, 
    LLAVEDER, IF, ELSE, ERROR, IDENTIFICADOR, BREAK, CONTINUE, PORNUMERO, EOT, AND, OR, ESPACIO
}